//mod append;
mod ansi;
mod autoview;
mod build_string;
mod char_;
mod def;
// mod contains;
// mod count;
mod each;
mod echo;
mod if_;
// mod inspect;
// mod length;
mod let_;
mod par_each;
// mod open;
// mod par_each;
// mod prepend;
mod seq;
mod str_collect;
mod str_to_int;

// mod str_length;
// mod sum;
// mod take;
// mod where_;

// pub use append::AppendCommand;
// pub use contains::ContainsCommand;
// pub use count::CountCommand;
// pub use inspect::InspectCommand;
// pub use length::LengthCommand;
pub use ansi::Command as Ansi;
pub use autoview::Autoview;
pub use build_string::BuildString;
pub use char_::Char;
pub use def::Def;
pub use each::Each;
pub use echo::Echo;
pub use if_::If;
pub use let_::Let;
pub use par_each::ParEach;
pub use seq::Seq;
pub use str_collect::SubCommand as StrCollect;
pub use str_to_int::SubCommand as StrToInt;
// pub use open::OpenCommand;
// pub use par_each::ParEachCommand;
// pub use prepend::PrependCommand;
// pub use str_length::StrLengthCommand;
// pub use sum::SumCommand;
// pub use take::TakeCommand;
// pub use where_::WhereCommand;
